# Ensures that ./script/go.bash works as intended with many versions of "go".
#
# See https://github.com/ooni/probe/issues/2664.

name: gobash
on:
  push:
    branches:
      - "release/**"
      - "fullbuild"
      - "gofixpathbuild"
      - "master"
    tags:
      - "v*"
  pull_request:
  schedule:
    - cron: "17 7 * * *"

jobs:
  build_with_specific_go_version:
    strategy:
      matrix:
        goversion:
          # When releasing ask yourself the question of whether to change this list
          - "1.16"
          - "1.17"
          - "1.18"
          - "1.19"
          - "1.20"
          - "1.21"
        system: [ubuntu-latest, macos-latest]
    runs-on: "${{ matrix.system }}"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.goversion }}"

      - run: ./script/go.bash run ./internal/cmd/buildtool generic miniooni
