# Ensures that ./script/go.bash works as intended with many versions of "go".
#
# See https://github.com/ooni/probe/issues/2664.

name: gobash
on:
  push:
    branches:
      - "release/**"
      - "fullbuild"
      - "gofixpathbuild"
      - "master"
    tags:
      - "v*"
  pull_request:
  schedule:
    - cron: "17 7 * * *"

jobs:
  build_with_specific_go_version:
    strategy:
      matrix:
        goversion:
          # When releasing, make sure this list contains the latest
          # stable version of Go as the last entry.
          - "1.15" # debian 11 "bullseye"
          - "1.16"
          - "1.17"
          - "1.18" # ubuntu 22.04 LTS
          - "1.19" # debian 12 "bookworm"
          - "1.20"
          - "1.21"
          - "1.22"
          - "1.23"
          - "1.24"
        system: [ubuntu-latest]
    runs-on: "${{ matrix.system }}"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.goversion }}"

      - run: ./script/go.bash run ./internal/cmd/buildtool generic miniooni
