# Ensures that ./internal/cmd/buildtool gofixpath {command} [arguments] downloads the correct
# version of go and executes {command} with [arguments] with "go" being the right version.

name: gofixpath
on:
  push:
    branches:
      - "release/**"
      - "fullbuild"
      - "gofixpathbuild"
      - "master"
    tags:
      - "v*"
  pull_request:
  schedule:
    - cron: "17 7 * * *"

jobs:
  build_with_specific_go_version:
    strategy:
      matrix:
        goversion: ["1.19", "1.20", "1.21"]
        system: [ubuntu-latest, macos-latest]
    runs-on: "${{ matrix.system }}"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.goversion }}"

      - run: go run ./internal/cmd/buildtool gofixpath -- go run ./internal/cmd/buildtool generic miniooni
