# Runs unit and integration tests for our fundamental networking library.
name: netxlite
on:
  # Because we link libc explicitly for getaddrinfo, we SHOULD run
  # these checks for every PR to ensure we still compile.
  pull_request:
  push:
    branches:
      - "master"
      - "release/**"
      - "fullbuild"

jobs:
  test_netxlite_package:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ "ubuntu-22.04", "windows-2022", "macos-12" ]
    steps:

      - uses: actions/checkout@v3

      - name: Get GOVERSION content
        id: goversion
        run: echo "version=$(cat GOVERSION)" >> "$GITHUB_OUTPUTS"
        shell: bash

      - uses: magnetikonline/action-golang-cache@v4
        with:
          go-version: "${{ steps.goversion.outputs.version }}"
          cache-key-suffix: "-coverage-${{ steps.goversion.outputs.version }}"

      # The first test compiles and links against libc and uses getaddrinfo
      - run: go test -race ./internal/netxlite/...

      # The second test instead uses netgo (we can't use -race with CGO_ENABLED=0)
      - run: go test ./internal/netxlite/...
        env:
          CGO_ENABLED: 0
